project:
  type: website

website:
  title: "webtest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: test.ipynb
        text: Test

execute:
  freeze: auto
  
format:
  html:
    theme: lumen
    css: styles.css
    toc: true



